=== datascience/plato/planning-core/src/main/resources/data/schemas/pcdl.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:annotation>
		<xsd:documentation xml:lang="en">
Schema for the description of preservation action tools and their context of use. This can be used to describe
seperate preservation action tools as well as tools put to a specific use (tools as part of a pathway)
</xsd:documentation>
	</xsd:annotation>
	<!-- Enumerations used by both migration and emulation tools -->
    <xsd:simpleType name="InterfaceType">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="GUI"/>
			<xsd:enumeration value="Command line"/>
			<xsd:enumeration value="Webservice"/>
			<xsd:enumeration value="API"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="StorageDevice">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="FloppyDisk"/>
			<xsd:enumeration value="CDRom"/>
			<xsd:enumeration value="Tape"/>
			<xsd:enumeration value="Cartridge"/>
			<xsd:enumeration value="USBStorageDevice"/>
			<xsd:enumeration value="Harddisk"/>
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="license">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="GPL"/>
			<xsd:enumeration value="LGPL or similar"></xsd:enumeration>
			<xsd:enumeration value="BSD"></xsd:enumeration>
			<xsd:enumeration value="Apache"></xsd:enumeration>
			<xsd:enumeration value="Public domain"></xsd:enumeration>			
			<xsd:enumeration value="Commercial"></xsd:enumeration>
			<xsd:enumeration value="Other?"></xsd:enumeration>
		</xsd:restriction>			
	</xsd:simpleType>
	
	<!-- for emulators -->
	<xsd:simpleType name="DataExtraction">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="none"/>
			<xsd:enumeration value="text"/>
			<xsd:enumeration value="images"/>
			<xsd:enumeration value="binary"/>
			<xsd:enumeration value="text, images"/>
			<xsd:enumeration value="images, binary"/>
			<xsd:enumeration value="text, images and binary"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="InputDevice">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="Mouse"/>
			<xsd:enumeration value="Keyboard"/>
			<xsd:enumeration value="Joystick"/>
			<xsd:enumeration value="Trackball"/>
			<xsd:enumeration value="Gamepad"/>
		</xsd:restriction>
	</xsd:simpleType>
<xsd:element name="pcdl">
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
The main element that can be used to wrap the descriptions of sets of pathways or sets of tools
</xsd:documentation>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="Pathway" type="Pathway" minOccurs="0" maxOccurs="unbounded"/>
				<xsd:element name="MigrationTool" type="MigrationTool" minOccurs="0" maxOccurs="unbounded"/>
				<xsd:element name="EmulationTool" type="EmulationTool" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:sequence>
			<xsd:attribute name="version" type="xsd:string" use="required"/>
		</xsd:complexType>
	</xsd:element>
	<!-- Definition for pathway -->
	<xsd:complexType name="Pathway">
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
UNSINN! wenn, dann ein allgemeiner pfad - nix tool-spezifisches.... 
This element is used to describe a collection of one or more tools that can be used to perform a preservation action. Such a set of tools is called a pathway.
</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="Description" type="xsd:string" minOccurs="0"/>
			<xsd:element name="EmulationTool" type="EmulationTool" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element name="MigrationTool" type="MigrationTool" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element name="Source" type="Provenance"/>
		</xsd:sequence>
		<xsd:attribute name="id" type="xsd:integer" use="required"/>
		<xsd:attribute name="status" type="xsd:string" use="required"/>
	</xsd:complexType>
	<!-- Definition for a file -->
	<xsd:complexType name="File">
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
This element describes a single file.
</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:any namespace="##local" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
			<!-- 'any'-element added for extensibility -->
		</xsd:sequence>
		<xsd:attribute name="type" use="required">
			<xsd:simpleType>
				<xsd:restriction base="xsd:string">
					<xsd:pattern value="(x-)?(fmt)/([0-9]*[a-z]*)+"/>
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="optional" type="xsd:string" use="required"/>
		<!-- Attribute for specifying the file type in the form of a PRONOM PUID. Regexp allows any PUID that contains an 'fmt'-token -->
	</xsd:complexType>
	<!-- Definition for a set of files -->
	<xsd:complexType name="FileSet">
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
This element describes a set of files. It's used to specify the set of files a tool can read or write.
</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="File" type="File" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
	<!-- Definition for an agent -->
	<xsd:complexType name="Agent">
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
This element is used to describe agents such as the creator of a software program. This
can be either an individual person or a company.
</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="Name" type="xsd:string"/>
			<xsd:element name="URL" type="xsd:anyURI"  minOccurs="0"></xsd:element>
			<xsd:element name="Description" type="xsd:string" minOccurs="0"/>
			<xsd:element name="Address" type="xsd:string" minOccurs="0"/>
			<xsd:element name="Website" type="xsd:string" minOccurs="0"/>
			<xsd:element name="Mail" type="xsd:string" minOccurs="0"/>
			<xsd:element name="Telephone" type="xsd:string" minOccurs="0"/>
			<xsd:element name="Support" type="xsd:boolean" minOccurs="0"/>
			<xsd:element name="Source" type="Provenance" minOccurs="0"/>
			<!--xsd:any namespace="##local" processContents="lax" minOccurs="0" maxOccurs="unbounded"/-->
		</xsd:sequence>
	</xsd:complexType>
	<!-- Definition for provenance information -->
	<xsd:complexType name="Provenance">
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
This element is used to keep track of the source of the information in the registry. It can be used to describe the person or organisation that provided the information in the first place, as well as the last person or organisation that modified the information. In addition, the date the information was submitted and modified for the last time can be stored here.
</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="SuppliedBy" type="Agent"/>
			<xsd:element name="SuppliedAt" type="xsd:dateTime"/>
			<xsd:element name="LastModifiedBy" type="Agent"/>
			<xsd:element name="LastModifiedAt" type="xsd:dateTime"/>
		</xsd:sequence>
	</xsd:complexType>
	<!-- Definition for documentation -->
	<xsd:complexType name="documents">
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
This element is used to store information on the documentation of a software product or hardware component
</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="Creator" type="Agent" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element name="Description" type="xsd:string" minOccurs="0"/>
			<xsd:element name="Location" type="xsd:anyURI"/>
			<xsd:element name="ReleaseDate" type="xsd:date"/>
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="resourceConsumption">
		<xsd:sequence>
			<xsd:element name="accumulatedAverageMilliSecondsPerMegabyte" type="accumulatedAverage"></xsd:element>
			<xsd:element name="accumulatedAverageMemory" type="accumulatedAverage"></xsd:element>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="accumulatedAverage">
		<xsd:sequence>
			<xsd:element name="numberOfItems" type="xsd:integer"></xsd:element>
			<xsd:element name="value" type="xsd:double"></xsd:element>
			<xsd:element name="unit" type="xsd:string"></xsd:element>
			<xsd:element name="variance" type="xsd:double"></xsd:element>
			<xsd:element name="min" type="xsd:double"></xsd:element>
			<xsd:element name="max" type="xsd:double"></xsd:element>
			<xsd:element name="description" type="xsd:string"></xsd:element>
			<xsd:element name="source" type="Provenance"></xsd:element>
		</xsd:sequence>
	</xsd:complexType>

	<!-- Definition for memoryspace -->
	<xsd:complexType name="MemorySpace">
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
This element is used to describe a certain memory size, measured in megabytes
</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="Amount" type="xsd:integer"/>
			<xsd:element name="Unit" default="MB" minOccurs="0"/>
		</xsd:sequence>
	</xsd:complexType>
	<!-- Definition for processorspeed -->
	<xsd:complexType name="ProcessorSpeed">
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="AmountMHz" type="xsd:integer"/>
			<xsd:element name="Unit" default="MHz" minOccurs="0"/>
		</xsd:sequence>
	</xsd:complexType>

	<!-- Definition for general information for a tool. -->
	<xsd:complexType name="GeneralInfo">
		<xsd:sequence> 
			<xsd:element name="Name" type="xsd:string" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element name="Version" type="xsd:string" minOccurs="0"/>
			<xsd:element name="Description" type="xsd:string" minOccurs="0"/>
			<xsd:element name="Location" type="xsd:anyURI" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element name="CreationDate" type="xsd:date" minOccurs="0"/>
			<xsd:element name="Developer" type="Agent" minOccurs="0" maxOccurs="unbounded"/>
			
			<xsd:element name="Interface" type="interface"></xsd:element>
			<xsd:element name="Licensing" type="licensing"></xsd:element>
			<xsd:element name="Documentation" type="documentation"></xsd:element>
			
			<!--xsd:any namespace="##local" processContents="lax" minOccurs="0" maxOccurs="unbounded"/-->
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="documentation">
		<xsd:sequence>
			<xsd:element name="InstallGuide" type="documents" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element name="UserGuide" type="documents" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
		<xsd:attribute name="exists" default="false"></xsd:attribute>
	</xsd:complexType>
	
	<xsd:complexType name="interface">
		<xsd:sequence>
			<xsd:element name="ProgrammingLanguage" type="xsd:string" minOccurs="0"/>
			<xsd:element name="InputFormat" type="FileSet" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element name="InputMaxSize" type="MemorySpace" minOccurs="0"/>
			<xsd:element name="InterfaceType" type="InterfaceType" maxOccurs="3"/>
			<xsd:element name="ProgrammingInterface" type="xsd:boolean" minOccurs="0"/>
			<xsd:element name="Languages" type="Languages"></xsd:element>
		</xsd:sequence>
		
	</xsd:complexType>
	
	<xsd:complexType name="licensing">
		<xsd:sequence>
			<xsd:element name="PriceEUROS" type="xsd:decimal"/>
			<xsd:element name="License" type="license" minOccurs="1" maxOccurs="unbounded"/>
			<xsd:element name="OpenSource" type="xsd:boolean"></xsd:element>
		</xsd:sequence>
	</xsd:complexType>


	<xsd:complexType name="Languages">
		<xsd:sequence>
			<xsd:element name="Language" type="xsd:language" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="Judgements">
		<xsd:sequence>
			<xsd:element name="Usability" type="accumulatedAverage" minOccurs="0"></xsd:element>
			<xsd:element name="Stability" type="accumulatedAverage" minOccurs="0"></xsd:element>
			<xsd:element name="ActivityLogging" type="accumulatedAverage" minOccurs="0"></xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	
	<!-- Definition for a technical environment -->
	<xsd:complexType name="TechnicalEnvironment">
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
This element describes a technical environment. This can be used to describe a technical environment that's required by
a software product (a 'host environment') or a technical environment that's offered by an emulator (a 'target environment').
</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="OperatingSystem" type="sfwPUID" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element name="ServicePack" type="xsd:string" minOccurs="0"/>
			<xsd:element name="ProcessorType" type="xsd:string" minOccurs="0"/>
			<xsd:element name="ProcessorSpeedMinimum" type="ProcessorSpeed" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element name="ProcessorSpeedRecommended" type="ProcessorSpeed" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element name="MemoryMinimum" type="MemorySpace" minOccurs="0"/>
			<xsd:element name="MemoryRecommended" type="MemorySpace"/>
			<xsd:element name="StorageSpaceMinimum" type="MemorySpace" minOccurs="0"/>
			<xsd:element name="StorageSpaceRecommended" type="MemorySpace"/>
			<xsd:element name="ScreenResolutionHMinimum" type="xsd:integer" minOccurs="0"/>
			<xsd:element name="ScreenResolutionHRecommended" type="xsd:integer" minOccurs="0"/>
			<xsd:element name="ScreenResolutionVMinimum" type="xsd:integer" minOccurs="0"/>
			<xsd:element name="ScreenResolutionVRecommended" type="xsd:integer" minOccurs="0"/>
			<xsd:element name="ScreenColourDepthMinimum" type="xsd:integer" minOccurs="0"/>
			<xsd:element name="ScreenColourDepthRecommended" type="xsd:integer" minOccurs="0"/>
			<xsd:element name="AudioBitDepthMinimum" type="xsd:integer" minOccurs="0"/>
			<xsd:element name="AudioBitDepthRecommended" type="xsd:integer" minOccurs="0"/>
			<xsd:element name="AudioChannelsMinimum" type="xsd:integer" minOccurs="0"/>
			<xsd:element name="AudioChannelsRecommended" type="xsd:integer" minOccurs="0"/>
			<xsd:element name="AudioSampleRate" type="xsd:integer" minOccurs="0"/>
			<xsd:element name="InputDevice" type="InputDevice" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element name="StorageDevice" type="StorageDevice" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element name="NetworkDevice" type="xsd:boolean" minOccurs="0"/>
			<xsd:element name="DataExtraction" type="DataExtraction" minOccurs="0"/>
			<!--xsd:any namespace="##local" processContents="lax" minOccurs="0" maxOccurs="unbounded"/-->
		</xsd:sequence>
	</xsd:complexType>
	<xsd:simpleType name="sfwPUID">
		<xsd:restriction base="xsd:string">
			<xsd:pattern value="(x-)?(sfw)/([0-9]*[a-z]*)+"/>
		</xsd:restriction>
	</xsd:simpleType>
	<!-- Definition for a software product -->
	<xsd:complexType name="SoftwareProduct">
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
Basic definition for a software product. This can be used to describe preservation action tools,
but also other software products such as operating systems. The MigrationTool and EmulationTool
elements are derived from this element
</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="GeneralInfo" type="GeneralInfo"/>
			<xsd:element name="HostEnvironment" type="TechnicalEnvironment" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element name="evaluation" type="Judgements"/>
			<xsd:element name="Source" type="Provenance"/>
		</xsd:sequence>
		<xsd:attribute name="id" type="sfwPUID"/>
	</xsd:complexType>
	<!-- Definition for emulation tool -->
	<xsd:complexType name="EmulationTool">
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
Definition for an emulation tool, derived from PreservationTool. This element is
used for describing 'tools for environments'. These are tools that can be used
to mimic a certain technical environment by means of emulation or virtualisation
</xsd:documentation>
		</xsd:annotation>
		<xsd:complexContent>
			<xsd:extension base="SoftwareProduct">
				<xsd:sequence>
					<xsd:element name="TargetEnvironment" type="TechnicalEnvironment" maxOccurs="unbounded"/>
				</xsd:sequence>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
	<!-- Definition for migration tool -->
	<xsd:complexType name="MigrationTool">
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
Definition for a migration tool; derived from PreservationTool. This element is
used for describing tools that can convert files from one type to another.
</xsd:documentation>
		</xsd:annotation>
		<xsd:complexContent>
			<xsd:extension base="SoftwareProduct">
				<xsd:sequence>
					<xsd:element name="OutputFormat" type="FileSet" maxOccurs="unbounded"/>
					<xsd:element name="BatchProcessing" type="xsd:boolean"/>
				</xsd:sequence>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
</xsd:schema>

=== datascience/plato/planning-core/src/main/resources/data/pcdl/dia.xml
<?xml version="1.0" encoding="UTF-8"?>
<pcdl xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="pcdl.xsd" version="1.1">
<MigrationTool id="x-sfw/381">
<GeneralInfo>
<Name>Dia</Name>
<Version>0.96.1</Version>
<Description>Dia is a diagram creation program released under the GPL license. It can load and save diagrams to a custom XML format, and can export diagrams to a number of formats, including EPS, SVG, XFIG, WMF and PNG.</Description>
<Location>http://www.gnome.org/projects/dia/</Location>

<CreationDate>2007-03-29</CreationDate>
<Developer>
<Name>Alexander Larsson</Name>
<Website/>
<Mail>alla@lysator.liu.se</Mail>
<Support>false</Support>
<Source>
<SuppliedBy>
<Name>Administrator</Name>
<Website>http://www.institute.com/johndoe</Website>
<Mail>johndoe@institute.org</Mail>
</SuppliedBy>
<SuppliedAt>2002-05-30T09:00:00</SuppliedAt>
<LastModifiedBy>
<Name>AnotherAdministrator</Name>
<Website>http://www.institute.org/another</Website>
<Mail>another@institute.org</Mail>
</LastModifiedBy>
<LastModifiedAt>2002-05-30T09:30:00</LastModifiedAt>
</Source>
</Developer>
    
    <Interface>
        <InputFormat>
            <File type="x-fmt/381" optional="true"/>
            <File type="fmt/84" optional="true"/>
        </InputFormat>
        <InputMaxSize>
            <Amount>48</Amount>
        </InputMaxSize>
        <InterfaceType>GUI</InterfaceType>
        <ProgrammingInterface>false</ProgrammingInterface>
        <Languages>
            <Language>en</Language>
        </Languages>
    </Interface>
    <Licensing>
        <PriceEUROS>0</PriceEUROS>
        <License>GPL</License>
        <OpenSource>true</OpenSource>
        <Schema>openSource</Schema>
    </Licensing>
    <Documentation>
        <UserGuide>
            <Creator>
                <Name>Kevin Breith</Name>
            </Creator>
            <Creator>
                <Name>Henry House</Name>
            </Creator>
            <Creator>
                <Name>Judith Samson</Name>
            </Creator>
            <Location>http://www.gnome.org/projects/dia/doc/dia-manual.pdf</Location>
            <ReleaseDate>2000-10-06</ReleaseDate>
        </UserGuide>
    </Documentation>

    
</GeneralInfo>
  
<HostEnvironment>
<OperatingSystem>sfw/183</OperatingSystem>
<OperatingSystem>x-sfw/37</OperatingSystem>
<OperatingSystem>x-sfw/31</OperatingSystem>
<OperatingSystem>x-sfw/9</OperatingSystem>
<OperatingSystem>x-sfw/8</OperatingSystem>
<ProcessorSpeedMinimum>
<AmountMHz>120</AmountMHz>
</ProcessorSpeedMinimum>
<ProcessorSpeedRecommended>
<AmountMHz>400</AmountMHz>
</ProcessorSpeedRecommended>
<MemoryMinimum>
<Amount>256</Amount>
</MemoryMinimum>
<MemoryRecommended>
<Amount>512</Amount>
</MemoryRecommended>
<StorageSpaceMinimum>
<Amount>4</Amount>
</StorageSpaceMinimum>
<StorageSpaceRecommended>
<Amount>12</Amount>
</StorageSpaceRecommended>
</HostEnvironment>
    <evaluation>
        <Usability>
            <numberOfItems>1</numberOfItems>
            <value>4.0</value>
            <unit>utility</unit>
            <variance>0</variance>
            <min>4.0</min>
            <max>4.0</max>
            <description>Current average from miniMEE</description>
            <source>
                <SuppliedBy>
                    <Name>miniMEE</Name>
                    <URL>www.ifs.tuwien.ac.at/dp/minimee</URL>
                </SuppliedBy>
                <SuppliedAt>2009-07-30T08:34:34</SuppliedAt>
                <LastModifiedBy>
                    <Name>cb</Name>
                </LastModifiedBy>
                <LastModifiedAt>2009-07-30T08:34:34</LastModifiedAt>
            </source>
        </Usability>
    </evaluation>
<Source>
<SuppliedBy>
<Name>Administrator</Name>
<Website>http://www.institute.com/johndoe</Website>
<Mail>johndoe@institute.org</Mail>
</SuppliedBy>
<SuppliedAt>2002-05-30T09:00:00</SuppliedAt>
<LastModifiedBy>
<Name>AnotherAdministrator</Name>
<Website>http://www.institute.org/another</Website>
<Mail>another@institute.org</Mail>
</LastModifiedBy>
<LastModifiedAt>2002-05-30T09:30:00</LastModifiedAt>
</Source>
<OutputFormat>
<File type="fmt/54" optional="false"/>
<File type="x-fmt/540" optional="false"/>
</OutputFormat>
<BatchProcessing>false</BatchProcessing>
</MigrationTool>
</pcdl>

=== datascience/plato/planning-core/src/main/resources/data/pcdl/ImageIO.xml
<?xml version="1.0" encoding="UTF-8"?>
<pcdl xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="pcdl.xsd" version="1.1">
<MigrationTool id="x-sfw/381">
<GeneralInfo>
<Name>ImageIO</Name>
    <Version>fake</Version>
    <Description>
this pcdl descriptor is for testing purposes only

    </Description>
    <Location>http://www.imagemagick.org/</Location>
<CreationDate>2009-12-27</CreationDate>
<Developer>
    <Name>ImageMagick Studio LLC</Name>
<Source>
<SuppliedBy>
<Name>Administrator</Name>
<Website>http://www.institute.com/johndoe</Website>
<Mail>johndoe@institute.org</Mail>
</SuppliedBy>
<SuppliedAt>2010-01-08T12:08:00</SuppliedAt>
<LastModifiedBy>
<Name>AnotherAdministrator</Name>
<Website>http://www.institute.org/another</Website>
<Mail>another@institute.org</Mail>
</LastModifiedBy>
<LastModifiedAt>2010-01-08T19:30:00</LastModifiedAt>
</Source>
</Developer>
    <Interface>
        <InputFormat>
            <File type="fmt/41" optional="true"/>
            <File type="fmt/42" optional="true"/>
            <File type="fmt/43" optional="true"/>
            <File type="fmt/44" optional="true"/>
            <File type="fmt/112" optional="true"/>
        </InputFormat>
        <InputMaxSize>
            <Amount>512</Amount>
        </InputMaxSize>
        <InterfaceType>GUI</InterfaceType>
        <InterfaceType>Command line</InterfaceType>
        <InterfaceType>API</InterfaceType>
        <ProgrammingInterface>true</ProgrammingInterface>
        <Languages>
            <Language>en</Language>
            <Language>de</Language>
            <Language>it</Language>
        </Languages>
    </Interface>
    <Licensing>
        <PriceEUROS>0</PriceEUROS>
        <License>GPL</License>
        <OpenSource>true</OpenSource>
        <Schema>openSource</Schema>
    </Licensing>
    <Documentation>
        <UserGuide>
            <Creator>
                <Name>unknown</Name>
            </Creator>
            <Location>http://www.imagemagick.org/script/convert.php?ImageMagick=55afgl5qq851oqh66thkbnba84</Location>
            <ReleaseDate>2000-10-06</ReleaseDate>
        </UserGuide>
    </Documentation>
</GeneralInfo>
<HostEnvironment>
<OperatingSystem>sfw/183</OperatingSystem>
<OperatingSystem>x-sfw/37</OperatingSystem>
<OperatingSystem>x-sfw/31</OperatingSystem>
<OperatingSystem>x-sfw/9</OperatingSystem>
<OperatingSystem>x-sfw/8</OperatingSystem>
<ProcessorSpeedMinimum>
<AmountMHz>120</AmountMHz>
</ProcessorSpeedMinimum>
<ProcessorSpeedRecommended>
<AmountMHz>400</AmountMHz>
</ProcessorSpeedRecommended>
<MemoryMinimum>
<Amount>256</Amount>
</MemoryMinimum>
<MemoryRecommended>
<Amount>512</Amount>
</MemoryRecommended>
<StorageSpaceMinimum>
<Amount>4</Amount>
</StorageSpaceMinimum>
<StorageSpaceRecommended>
<Amount>12</Amount>
</StorageSpaceRecommended>
</HostEnvironment>
    <evaluation>
        <Usability>
            <numberOfItems>1</numberOfItems>
            <value>4.0</value>
            <unit>utility</unit>
            <variance>0</variance>
            <min>4.0</min>
            <max>4.0</max>
            <description>Current average from miniMEE</description>
            <source>
                <SuppliedBy>
                    <Name>miniMEE</Name>
                    <URL>www.ifs.tuwien.ac.at/dp/minimee</URL>
                </SuppliedBy>
                <SuppliedAt>2009-07-30T08:34:34</SuppliedAt>
                <LastModifiedBy>
                    <Name>cb</Name>
                </LastModifiedBy>
                <LastModifiedAt>2009-07-30T08:34:34</LastModifiedAt>
            </source>
        </Usability>
    </evaluation>
<Source>
<SuppliedBy>
<Name>Administrator</Name>
<Website>http://www.institute.com/johndoe</Website>
<Mail>johndoe@institute.org</Mail>
</SuppliedBy>
<SuppliedAt>2002-05-30T09:00:00</SuppliedAt>
<LastModifiedBy>
<Name>AnotherAdministrator</Name>
<Website>http://www.institute.org/another</Website>
<Mail>another@institute.org</Mail>
</LastModifiedBy>
<LastModifiedAt>2002-05-30T09:30:00</LastModifiedAt>
</Source>
<OutputFormat>
    <File type="fmt/152" optional="false"/>
    <File type="x-fmt/399" optional="false"/>
    <File type="x-fmt/388" optional="false"/>
    <File type="x-fmt/7" optional="false"/>
    <File type="x-fmt/387" optional="false"/>
    <File type="x-fmt/8" optional="false"/>
</OutputFormat>
<BatchProcessing>true</BatchProcessing>
</MigrationTool>
</pcdl>
